language: php

install:
  - docker run -d --name $containername $imagename
  - docker exec $containername service apache2 restart 
script:
  - php codecept.phar run unit

before-script:
env:
  # global will stay the same across all matrix possibilities (will not create additional combinations to run)
  global:
    - imagename=apacheimage
    - containername=apachemysql

notifications: # set notification options
  email:
    recipients:
      - thulana@orangehrm.us.com
      - thulanakannangara@gmail.com

    # change is when the repo status goes from pass to fail or vice versa
    on_success: always
    on_failure: always

services:
  - docker

before_install:
  - php --version
  - docker build -t $imagename .
  - sudo apt-get update
  - composer self-update
